# Generated by Django 3.1.7 on 2021-03-22 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Food',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('price', models.FloatField()),
                ('quantity', models.IntegerField()),
                ('type', models.CharField(max_length=30)),
                ('category', models.CharField(max_length=30)),
                ('image', models.ImageField(default='', upload_to='media')),
            ],
            options={
                'db_table': 'foodDB',
            },
        ),
    ]
