# Generated by Django 3.2 on 2021-05-09 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FoodApp', '0002_auto_20210509_2317'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordersummery1',
            name='date',
            field=models.CharField(blank=True, default='2021-05-09 23:20', max_length=25),
        ),
    ]
