# Generated by Django 3.2 on 2021-05-09 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FoodApp', '0003_alter_ordersummery1_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordersummery1',
            name='date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
